language: c
compiler: gcc

sudo: required
dist: trusty

env:
  global:
    - MAKE_CMD="make -j2"

before_script:  .ci/before_script.sh
script:         .ci/script.sh

addons:
  apt:
    sources:
      - sourceline: 'ppa:vala-team/ppa'
    packages:
      - autoconf
      - autoconf-archive
      - automake
      - docbook-xsl
      - gettext
      - libtool
      - intltool
      - gobject-introspection
      - libcomedi-dev
      - libgee-0.8-dev
      - libglib2.0-dev
      - libgirepository1.0-dev
      - libgsl0-dev
      - libjson-glib-dev
      - libmatheval-dev
      - libmodbus-dev
      - libpeas-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libvala-0.30-dev
      - libxml2-dev
      - libzmq3-dev
      - python-gi-dev
      - valac-0.30

notifications:
  slack: opendcs:3d3YMfezT8S8vBHlpyJvTAic
